// ─────────────────────────────────────────────────────────────────
// MCP TEE Server — Azure Confidential Container on ACI
//
// Deploys:
//   1. ACI Container Group (sku: Confidential, AMD SEV-SNP)
//   2. Azure Key Vault with mHSM key-release policy
//   3. Managed Identity for the container to call AKV
//   4. Azure Container Registry reference
//
// The CCE security policy (base64) must be generated BEFORE deployment
// using the confcom CLI and passed as a parameter.
//
// Usage:
//   az deployment group create \
//     --resource-group <rg> \
//     --template-file infra/main.bicep \
//     --parameters \
//         acrName=<acr> \
//         imageTag=latest \
//         ccePolicy=<base64-policy>
// ─────────────────────────────────────────────────────────────────

@description('Name of the Azure Container Registry holding the MCP server image')
param acrName string

@description('Image tag to deploy')
param imageTag string = 'latest'

@description('Base64-encoded CCE security policy (generated by az confcom acipolicy gen)')
@secure()
param ccePolicy string

@description('Azure region for all resources')
param location string = resourceGroup().location

@description('Name prefix for all resources')
param namePrefix string = 'mcp-tee'


@description('Object ID of the deployer (for Key Vault access policy). Get with: az ad signed-in-user show --query id -o tsv')
param deployerObjectId string = ''

@description('ACR admin password (used when managed identity lacks AcrPull role)')
@secure()
param acrPassword string = ''

@description('MAA (Microsoft Azure Attestation) endpoint for the SKR sidecar')
param maaEndpoint string = 'sharedeus.eus.attest.azure.net'

@description('Name of the RSA-HSM envelope key in Key Vault (used by SKR to decrypt secrets)')
param envelopeKeyName string = 'mcp-envelope-key'

@description('RSA-encrypted GitHub token (base64). Encrypt with: python scripts/encrypt_secret.py')
@secure()
param encGithubToken string = ''

@description('RSA-encrypted database connection string (base64)')
@secure()
param encDbConnectionString string = ''

@description('RSA-encrypted webhook URL (base64)')
@secure()
param encWebhookUrl string = ''

// ── Variables ───────────────────────────────────────────────────
var containerGroupName = '${namePrefix}-server'
var keyVaultName = '${namePrefix}-kv-${uniqueString(resourceGroup().id)}'
var managedIdentityName = '${namePrefix}-identity'
var imageName = '${acrName}.azurecr.io/mcp-tee-server:${imageTag}'
var skrImage = 'mcr.microsoft.com/aci/skr:2.9'

// ── Managed Identity ────────────────────────────────────────────
resource managedIdentity 'Microsoft.ManagedIdentity/userAssignedIdentities@2023-01-31' = {
  name: managedIdentityName
  location: location
}

// ── Key Vault (for envelope key with key-release policy) ──────
resource keyVault 'Microsoft.KeyVault/vaults@2023-07-01' = {
  name: keyVaultName
  location: location
  properties: {
    sku: {
      family: 'A'
      name: 'premium' // Required for HSM-backed keys and Secure Key Release (SKR)
    }
    tenantId: subscription().tenantId
    // Use access policies (works with Contributor role; RBAC requires Owner/UAA)
    enableRbacAuthorization: false
    enableSoftDelete: true
    softDeleteRetentionInDays: 7
    accessPolicies: concat(
      // Managed identity: needs key release permission for SKR sidecar
      [
        {
          tenantId: subscription().tenantId
          objectId: managedIdentity.properties.principalId
          permissions: {
            keys: [ 'get', 'release' ]
          }
        }
      ],
      // Deployer: needs key create/get/list to provision envelope key
      deployerObjectId != '' ? [
        {
          tenantId: subscription().tenantId
          objectId: deployerObjectId
          permissions: {
            keys: [ 'get', 'list', 'create', 'import', 'update', 'delete', 'purge', 'encrypt', 'wrapKey', 'release' ]
          }
        }
      ] : []
    )
    networkAcls: {
      defaultAction: 'Allow' // Allow access from deployer's workstation
      bypass: 'AzureServices'
    }
  }
}

// ── Key Vault Keys ───────────────────────────────────────────
// A single RSA-HSM key (the "envelope key") is used for envelope encryption.
// Secrets are encrypted with its public key at provisioning time and passed
// as ENC_* env vars. At runtime, the SKR sidecar releases the private key
// (after hardware attestation) and the server decrypts them in memory.
//
// Create the key AFTER deployment:
//   az keyvault key create --vault-name <kv> --name mcp-envelope-key \
//     --kty RSA-HSM --size 4096 --exportable true \
//     --policy @infra/key-release-policy.json

// ── Key Vault access is managed via access policies above ──────
// (RBAC role assignments not needed — access policies work with Contributor)

// ── ACI Confidential Container Group ────────────────────────────
resource containerGroup 'Microsoft.ContainerInstance/containerGroups@2023-05-01' = {
  name: containerGroupName
  location: location
  identity: {
    type: 'UserAssigned'
    userAssignedIdentities: {
      '${managedIdentity.id}': {}
    }
  }
  properties: {
    // ─── Confidential Computing SKU ───────────────────────────
    sku: 'Confidential'
    confidentialComputeProperties: {
      ccePolicy: ccePolicy // Hardware-enforced security policy
    }

    osType: 'Linux'
    restartPolicy: 'OnFailure'

    // ─── Container Image ──────────────────────────────────────
    containers: [
      {
        name: 'mcp-server'
        properties: {
          image: imageName
          resources: {
            requests: {
              cpu: 1
              memoryInGB: 2
            }
          }
          environmentVariables: [
            {
              name: 'SKR_ENDPOINT'
              value: 'http://localhost:9000'
            }
            {
              name: 'MAA_ENDPOINT'
              value: maaEndpoint
            }
            {
              name: 'AKV_ENDPOINT'
              value: keyVault.properties.vaultUri
            }
            {
              name: 'ENVELOPE_KEY_NAME'
              value: envelopeKeyName
            }
            {
              name: 'IDENTITY_CLIENT_ID'
              value: managedIdentity.properties.clientId
            }
            {
              name: 'ENC_GITHUB_TOKEN'
              secureValue: encGithubToken
            }
            {
              name: 'ENC_DB_CONNECTION_STRING'
              secureValue: encDbConnectionString
            }
            {
              name: 'ENC_WEBHOOK_URL'
              secureValue: encWebhookUrl
            }
          ]
          ports: [
            {
              port: 8080
              protocol: 'TCP'
            }
          ]
        }
      }
      {
        name: 'skr-sidecar'
        properties: {
          image: skrImage
          resources: {
            requests: {
              cpu: 1
              memoryInGB: 1
            }
          }
          command: [
            '/bin/skr'
            '-port'
            '9000'
          ]
          ports: [
            {
              port: 9000
              protocol: 'TCP'
            }
          ]
        }
      }
    ]

    // ─── Network: expose the MCP server port ──────────────────
    ipAddress: {
      type: 'Public'
      dnsNameLabel: containerGroupName
      ports: [
        {
          port: 8080
          protocol: 'TCP'
        }
      ]
    }

    // ─── Image Registry Credentials ───────────────────────────
    imageRegistryCredentials: [
      acrPassword != '' ? {
        server: '${acrName}.azurecr.io'
        username: acrName
        password: acrPassword
      } : {
        server: '${acrName}.azurecr.io'
        identity: managedIdentity.id
      }
    ]
  }
}

// ── Outputs ─────────────────────────────────────────────────────
output containerGroupId string = containerGroup.id
output containerGroupName string = containerGroup.name
output keyVaultName string = keyVault.name
output keyVaultUri string = keyVault.properties.vaultUri
output managedIdentityClientId string = managedIdentity.properties.clientId
output serverFqdn string = containerGroup.properties.ipAddress.fqdn
