// ─────────────────────────────────────────────────────────────────
// MCP TEE Server — Azure Confidential Container on ACI
//
// Deploys:
//   1. ACI Container Group (sku: Confidential, AMD SEV-SNP)
//   2. Azure Key Vault with mHSM key-release policy
//   3. Managed Identity for the container to call AKV
//   4. Azure Container Registry reference
//
// The CCE security policy (base64) must be generated BEFORE deployment
// using the confcom CLI and passed as a parameter.
//
// Usage:
//   az deployment group create \
//     --resource-group <rg> \
//     --template-file infra/main.bicep \
//     --parameters \
//         acrName=<acr> \
//         imageTag=latest \
//         ccePolicy=<base64-policy>
// ─────────────────────────────────────────────────────────────────

@description('Name of the Azure Container Registry holding the MCP server image')
param acrName string

@description('Image tag to deploy')
param imageTag string = 'latest'

@description('Base64-encoded CCE security policy (generated by az confcom acipolicy gen)')
@secure()
param ccePolicy string

@description('Azure region for all resources')
param location string = resourceGroup().location

@description('Name prefix for all resources')
param namePrefix string = 'mcp-tee'

@description('Set to false to skip RBAC role assignment (useful when lacking Owner/UAA permissions)')
param deployRbac bool = true

@description('ACR admin password (used when managed identity lacks AcrPull role)')
@secure()
param acrPassword string = ''

@description('MAA (Microsoft Azure Attestation) endpoint for the SKR sidecar')
param maaEndpoint string = 'sharedeus.eus.attest.azure.net'

// ── Variables ───────────────────────────────────────────────────
var containerGroupName = '${namePrefix}-server'
var keyVaultName = '${namePrefix}-kv-${uniqueString(resourceGroup().id)}'
var managedIdentityName = '${namePrefix}-identity'
var imageName = '${acrName}.azurecr.io/mcp-tee-server:${imageTag}'
var skrImage = 'mcr.microsoft.com/aci/skr:2.9'

// ── Managed Identity ────────────────────────────────────────────
resource managedIdentity 'Microsoft.ManagedIdentity/userAssignedIdentities@2023-01-31' = {
  name: managedIdentityName
  location: location
}

// ── Key Vault (for secret storage with key-release policy) ──────
resource keyVault 'Microsoft.KeyVault/vaults@2023-07-01' = {
  name: keyVaultName
  location: location
  properties: {
    sku: {
      family: 'A'
      name: 'premium' // Required for HSM-backed keys and Secure Key Release (SKR) policies
    }
    tenantId: subscription().tenantId
    enableRbacAuthorization: true
    enableSoftDelete: true
    softDeleteRetentionInDays: 7
    networkAcls: {
      defaultAction: 'Deny'
      bypass: 'AzureServices'
    }
  }
}

// ── Key Vault Keys ───────────────────────────────────────────
// Secrets are stored as exportable Key Vault keys with a release policy.
// The SKR sidecar performs hardware attestation and calls AKV to release
// them at runtime. Keys must be imported AFTER deployment using:
//   az keyvault key import --vault-name <kv> --name <key-name> \
//     --kty oct-HSM --ops export --exportable true \
//     --policy infra/key-release-policy.json --value <base64-secret>

// ── RBAC: Grant the managed identity access to Key Vault key release ─
// Role: Key Vault Crypto Service Release User (08bbd89a-735e-4713-a852-15bf7196a6c7)
resource kvRoleAssignment 'Microsoft.Authorization/roleAssignments@2022-04-01' = if (deployRbac) {
  name: guid(keyVault.id, managedIdentity.id, '08bbd89a-735e-4713-a852-15bf7196a6c7')
  scope: keyVault
  properties: {
    roleDefinitionId: subscriptionResourceId(
      'Microsoft.Authorization/roleDefinitions',
      '08bbd89a-735e-4713-a852-15bf7196a6c7'
    )
    principalId: managedIdentity.properties.principalId
    principalType: 'ServicePrincipal'
  }
}

// ── ACI Confidential Container Group ────────────────────────────
resource containerGroup 'Microsoft.ContainerInstance/containerGroups@2023-05-01' = {
  name: containerGroupName
  location: location
  identity: {
    type: 'UserAssigned'
    userAssignedIdentities: {
      '${managedIdentity.id}': {}
    }
  }
  properties: {
    // ─── Confidential Computing SKU ───────────────────────────
    sku: 'Confidential'
    confidentialComputeProperties: {
      ccePolicy: ccePolicy // Hardware-enforced security policy
    }

    osType: 'Linux'
    restartPolicy: 'OnFailure'

    // ─── Container Image ──────────────────────────────────────
    containers: [
      {
        name: 'mcp-server'
        properties: {
          image: imageName
          resources: {
            requests: {
              cpu: 1
              memoryInGB: 2
            }
          }
          environmentVariables: [
            {
              name: 'SKR_ENDPOINT'
              value: 'http://localhost:9000'
            }
            {
              name: 'MAA_ENDPOINT'
              value: maaEndpoint
            }
            {
              name: 'AKV_ENDPOINT'
              value: keyVault.properties.vaultUri
            }
          ]
          ports: [
            {
              port: 8080
              protocol: 'TCP'
            }
          ]
        }
      }
      {
        name: 'skr-sidecar'
        properties: {
          image: skrImage
          resources: {
            requests: {
              cpu: 1
              memoryInGB: 1
            }
          }
          command: [
            '/bin/skr'
            '-port'
            '9000'
          ]
          ports: [
            {
              port: 9000
              protocol: 'TCP'
            }
          ]
        }
      }
    ]

    // ─── Network: expose the MCP server port ──────────────────
    ipAddress: {
      type: 'Public'
      dnsNameLabel: containerGroupName
      ports: [
        {
          port: 8080
          protocol: 'TCP'
        }
      ]
    }

    // ─── Image Registry Credentials ───────────────────────────
    imageRegistryCredentials: [
      acrPassword != '' ? {
        server: '${acrName}.azurecr.io'
        username: acrName
        password: acrPassword
      } : {
        server: '${acrName}.azurecr.io'
        identity: managedIdentity.id
      }
    ]
  }
}

// ── Outputs ─────────────────────────────────────────────────────
output containerGroupId string = containerGroup.id
output containerGroupName string = containerGroup.name
output keyVaultName string = keyVault.name
output keyVaultUri string = keyVault.properties.vaultUri
output managedIdentityClientId string = managedIdentity.properties.clientId
output serverFqdn string = containerGroup.properties.ipAddress.fqdn
